# Generated by Django 4.0.3 on 2022-08-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_do', models.TextField()),
                ('task_creation_time', models.DateTimeField(auto_now_add=True)),
                ('completion', models.BooleanField(default=False)),
            ],
        ),
    ]
